name: CI

# Triggers: push y pull_request a main
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    # 1. Checkout del repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup del runtime (Node.js)
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # 3. Instalación de dependencias con cache
    - name: Install dependencies
      run: npm ci

    # 4. Ejecución de pruebas unitarias con cobertura
    - name: Run tests
      run: npm run test:ci

    # 5. Publicación de artefactos - Subir reportes de cobertura
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    # Publicar reporte de cobertura como artefacto
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report-node-${{ matrix.node-version }}
        path: |
          coverage/
          !coverage/tmp/

    # Publicar logs de test como artefacto
    - name: Upload test logs
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: test-logs-node-${{ matrix.node-version }}
        path: |
          npm-debug.log*
          yarn-debug.log*
          yarn-error.log*

  # Job adicional para verificar el formato del código (opcional pero recomendado)
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # Si tienes ESLint configurado, descomenta las siguientes líneas:
    # - name: Run linter
    #   run: npm run lint

  # Job para verificar la seguridad de dependencias
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run security audit
      run: npm audit --audit-level=moderate
